export const DBC_TABS = [
  { key: "creature_display_info", label: "CreatureDisplayInfo", source: "dbc" },
  { key: "creature_model_data", label: "CreatureModelData", source: "dbc" },
  { key: "spell", label: "Spell", source: "dbc" },
  { key: "item", label: "Item", source: "dbc" },
  { key: "creature_template", label: "CreatureTemplate", source: "sql" },
  { key: "creature_model_info", label: "CreatureModelInfo", source: "sql" },
  { key: "item_template", label: "ItemTemplate", source: "sql" },
];

export const QUALITY_OPTIONS = [
  { value: 0, label: "Poor 劣质" },
  { value: 1, label: "Common 普通" },
  { value: 2, label: "Uncommon 优秀" },
  { value: 3, label: "Rare 精良" },
  { value: 4, label: "Epic 史诗" },
  { value: 5, label: "Legendary 传说" },
  { value: 6, label: "Artifact 神器" },
  { value: 7, label: "Heirloom 传家宝" },
];

export const CLASS_FLAGS = [
  { value: 1, label: "Warrior 战士" },
  { value: 2, label: "Paladin 圣骑士" },
  { value: 4, label: "Hunter 猎人" },
  { value: 8, label: "Rogue 盗贼" },
  { value: 16, label: "Priest 牧师" },
  { value: 32, label: "Death Knight 死亡骑士" },
  { value: 64, label: "Shaman 萨满" },
  { value: 128, label: "Mage 法师" },
  { value: 256, label: "Warlock 术士" },
  { value: 1024, label: "Druid 德鲁伊" },
];

export const RACE_FLAGS = [
  { value: 1, label: "Human 人类" },
  { value: 2, label: "Orc 兽人" },
  { value: 4, label: "Dwarf 矮人" },
  { value: 8, label: "Night Elf 暗夜精灵" },
  { value: 16, label: "Undead 亡灵" },
  { value: 32, label: "Tauren 牛头人" },
  { value: 64, label: "Gnome 侏儒" },
  { value: 128, label: "Troll 巨魔" },
  { value: 512, label: "Blood Elf 血精灵" },
  { value: 1024, label: "Draenei 德莱尼" },
];

// 枚举来源：azerothcore-wotlk/src/server/game/Entities/Item/ItemTemplate.h
// 及 https://github.com/azerothcore/wiki item_template 文档

export const ITEM_CLASS_OPTIONS = [
  { value: 0, label: "0 Consumable 消耗品" },
  { value: 1, label: "1 Container 容器" },
  { value: 2, label: "2 Weapon 武器" },
  { value: 3, label: "3 Gem 宝石" },
  { value: 4, label: "4 Armor 护甲" },
  { value: 5, label: "5 Reagent 材料" },
  { value: 6, label: "6 Projectile 弹药" },
  { value: 7, label: "7 Trade Goods 贸易商品" },
  { value: 8, label: "8 Generic 通用（已废弃）" },
  { value: 9, label: "9 Recipe 配方" },
  { value: 10, label: "10 Money 货币（已废弃）" },
  { value: 11, label: "11 Quiver 箭袋" },
  { value: 12, label: "12 Quest 任务物品" },
  { value: 13, label: "13 Key 钥匙" },
  { value: 14, label: "14 Permanent 永久（已废弃）" },
  { value: 15, label: "15 Miscellaneous 杂项" },
  { value: 16, label: "16 Glyph 雕文" },
];

// SubClass 的含义取决于 Class，按 Class ID 分组（ItemTemplate.h 中各 ItemSubclass* 枚举）
export const ITEM_SUBCLASS_OPTIONS: Record<number, { value: number; label: string }[]> = {
  0: [
    { value: 0, label: "0 Consumable 消耗品" },
    { value: 1, label: "1 Potion 药水" },
    { value: 2, label: "2 Elixir 药剂" },
    { value: 3, label: "3 Flask 合剂" },
    { value: 4, label: "4 Scroll 卷轴" },
    { value: 5, label: "5 Food & Drink 食物与饮料" },
    { value: 6, label: "6 Item Enhancement 物品强化" },
    { value: 7, label: "7 Bandage 绷带" },
    { value: 8, label: "8 Other 其他" },
  ],
  1: [
    { value: 0, label: "0 Container 容器" },
    { value: 1, label: "1 Soul Container 灵魂袋" },
    { value: 2, label: "2 Herb Container 草药袋" },
    { value: 3, label: "3 Enchanting Container 附魔袋" },
    { value: 4, label: "4 Engineering Container 工程袋" },
    { value: 5, label: "5 Gem Container 宝石袋" },
    { value: 6, label: "6 Mining Container 采矿袋" },
    { value: 7, label: "7 Leatherworking Container 制皮袋" },
    { value: 8, label: "8 Inscription Container 铭文袋" },
  ],
  2: [
    { value: 0, label: "0 Axe 单手斧" },
    { value: 1, label: "1 Two-Handed Axe 双手斧" },
    { value: 2, label: "2 Bow 弓" },
    { value: 3, label: "3 Gun 枪械" },
    { value: 4, label: "4 Mace 单手锤" },
    { value: 5, label: "5 Two-Handed Mace 双手锤" },
    { value: 6, label: "6 Polearm 长柄武器" },
    { value: 7, label: "7 Sword 单手剑" },
    { value: 8, label: "8 Two-Handed Sword 双手剑" },
    { value: 9, label: "9 Obsolete 已废弃" },
    { value: 10, label: "10 Staff 法杖" },
    { value: 11, label: "11 Exotic 特殊武器" },
    { value: 12, label: "12 Exotic 2 特殊武器 2" },
    { value: 13, label: "13 Fist Weapon 拳套" },
    { value: 14, label: "14 Miscellaneous 杂项" },
    { value: 15, label: "15 Dagger 匕首" },
    { value: 16, label: "16 Thrown 投掷武器" },
    { value: 17, label: "17 Spear 长矛" },
    { value: 18, label: "18 Crossbow 弩" },
    { value: 19, label: "19 Wand 魔杖" },
    { value: 20, label: "20 Fishing Pole 鱼竿" },
  ],
  3: [
    { value: 0, label: "0 Red 红色宝石" },
    { value: 1, label: "1 Blue 蓝色宝石" },
    { value: 2, label: "2 Yellow 黄色宝石" },
    { value: 3, label: "3 Purple 紫色宝石" },
    { value: 4, label: "4 Green 绿色宝石" },
    { value: 5, label: "5 Orange 橙色宝石" },
    { value: 6, label: "6 Meta 多彩宝石" },
    { value: 7, label: "7 Simple 简易宝石" },
    { value: 8, label: "8 Prismatic 棱彩宝石" },
  ],
  4: [
    { value: 0, label: "0 Miscellaneous 杂项" },
    { value: 1, label: "1 Cloth 布甲" },
    { value: 2, label: "2 Leather 皮甲" },
    { value: 3, label: "3 Mail 锁甲" },
    { value: 4, label: "4 Plate 板甲" },
    { value: 5, label: "5 Buckler 小圆盾（已废弃）" },
    { value: 6, label: "6 Shield 盾牌" },
    { value: 7, label: "7 Libram 圣契" },
    { value: 8, label: "8 Idol 神像" },
    { value: 9, label: "9 Totem 图腾" },
    { value: 10, label: "10 Sigil 魔印" },
  ],
  5: [{ value: 0, label: "0 Reagent 材料" }],
  6: [
    { value: 0, label: "0 Wand 魔杖（已废弃）" },
    { value: 1, label: "1 Bolt 弩箭（已废弃）" },
    { value: 2, label: "2 Arrow 箭矢" },
    { value: 3, label: "3 Bullet 子弹" },
    { value: 4, label: "4 Thrown 投掷（已废弃）" },
  ],
  7: [
    { value: 0, label: "0 Trade Goods 贸易商品" },
    { value: 1, label: "1 Parts 零件" },
    { value: 2, label: "2 Explosives 爆炸物" },
    { value: 3, label: "3 Devices 装置" },
    { value: 4, label: "4 Jewelcrafting 珠宝加工" },
    { value: 5, label: "5 Cloth 布料" },
    { value: 6, label: "6 Leather 皮革" },
    { value: 7, label: "7 Metal & Stone 金属与矿石" },
    { value: 8, label: "8 Meat 肉类" },
    { value: 9, label: "9 Herb 草药" },
    { value: 10, label: "10 Elemental 元素" },
    { value: 11, label: "11 Other 其他" },
    { value: 12, label: "12 Enchanting 附魔" },
    { value: 13, label: "13 Material 材料" },
    { value: 14, label: "14 Armor Enchantment 护甲附魔" },
    { value: 15, label: "15 Weapon Enchantment 武器附魔" },
  ],
  8: [{ value: 0, label: "0 Generic 通用" }],
  9: [
    { value: 0, label: "0 Book 书籍" },
    { value: 1, label: "1 Leatherworking 制皮图样" },
    { value: 2, label: "2 Tailoring 裁缝图样" },
    { value: 3, label: "3 Engineering 工程结构图" },
    { value: 4, label: "4 Blacksmithing 锻造图纸" },
    { value: 5, label: "5 Cooking 烹饪食谱" },
    { value: 6, label: "6 Alchemy 炼金配方" },
    { value: 7, label: "7 First Aid 急救手册" },
    { value: 8, label: "8 Enchanting 附魔公式" },
    { value: 9, label: "9 Fishing 钓鱼手册" },
    { value: 10, label: "10 Jewelcrafting 珠宝设计图" },
  ],
  10: [{ value: 0, label: "0 Money 货币" }],
  11: [
    { value: 0, label: "0 Quiver 箭袋（已废弃）" },
    { value: 1, label: "1 Quiver 箭袋（已废弃）" },
    { value: 2, label: "2 Quiver 箭袋" },
    { value: 3, label: "3 Ammo Pouch 弹药袋" },
  ],
  12: [{ value: 0, label: "0 Quest 任务" }],
  13: [
    { value: 0, label: "0 Key 钥匙" },
    { value: 1, label: "1 Lockpick 开锁工具" },
  ],
  14: [{ value: 0, label: "0 Permanent 永久" }],
  15: [
    { value: 0, label: "0 Junk 垃圾" },
    { value: 1, label: "1 Reagent 材料" },
    { value: 2, label: "2 Pet 宠物" },
    { value: 3, label: "3 Holiday 节日" },
    { value: 4, label: "4 Other 其他" },
    { value: 5, label: "5 Mount 坐骑" },
  ],
  16: [
    { value: 1, label: "1 Warrior 战士" },
    { value: 2, label: "2 Paladin 圣骑士" },
    { value: 3, label: "3 Hunter 猎人" },
    { value: 4, label: "4 Rogue 盗贼" },
    { value: 5, label: "5 Priest 牧师" },
    { value: 6, label: "6 Death Knight 死亡骑士" },
    { value: 7, label: "7 Shaman 萨满" },
    { value: 8, label: "8 Mage 法师" },
    { value: 9, label: "9 Warlock 术士" },
    { value: 11, label: "11 Druid 德鲁伊" },
  ],
};

// 来源：azerothcore/wiki item_template#Material（与 AscEmu ItemDefines.hpp 一致）
export const MATERIAL_OPTIONS = [
  { value: -1, label: "-1 Consumables 消耗品（食物、材料等）" },
  { value: 0, label: "0 Not Defined 未定义" },
  { value: 1, label: "1 Metal 金属" },
  { value: 2, label: "2 Wood 木材" },
  { value: 3, label: "3 Liquid 液体" },
  { value: 4, label: "4 Jewelry 珠宝" },
  { value: 5, label: "5 Chain 锁甲" },
  { value: 6, label: "6 Plate 板甲" },
  { value: 7, label: "7 Cloth 布甲" },
  { value: 8, label: "8 Leather 皮甲" },
];

// 来源：ItemTemplate.h enum InventoryType / azerothcore/wiki item_template#InventoryType
export const INVENTORY_TYPE_OPTIONS = [
  { value: 0, label: "0 Non equipable 不可装备" },
  { value: 1, label: "1 Head 头部" },
  { value: 2, label: "2 Neck 颈部" },
  { value: 3, label: "3 Shoulder 肩部" },
  { value: 4, label: "4 Shirt 衬衣" },
  { value: 5, label: "5 Chest 胸部" },
  { value: 6, label: "6 Waist 腰部" },
  { value: 7, label: "7 Legs 腿部" },
  { value: 8, label: "8 Feet 脚部" },
  { value: 9, label: "9 Wrists 手腕" },
  { value: 10, label: "10 Hands 手部" },
  { value: 11, label: "11 Finger 手指" },
  { value: 12, label: "12 Trinket 饰品" },
  { value: 13, label: "13 One-Hand 单手" },
  { value: 14, label: "14 Shield 盾牌" },
  { value: 15, label: "15 Ranged 远程（弓）" },
  { value: 16, label: "16 Back 背部" },
  { value: 17, label: "17 Two-Hand 双手" },
  { value: 18, label: "18 Bag 背包" },
  { value: 19, label: "19 Tabard 战袍" },
  { value: 20, label: "20 Robe 长袍" },
  { value: 21, label: "21 Main hand 主手" },
  { value: 22, label: "22 Off Hand 副手武器" },
  { value: 23, label: "23 Held in Off-Hand 副手物品" },
  { value: 24, label: "24 Ammo 弹药" },
  { value: 25, label: "25 Thrown 投掷" },
  { value: 26, label: "26 Ranged right 远程右（魔杖、枪械）" },
  { value: 27, label: "27 Quiver 箭袋" },
  { value: 28, label: "28 Relic 圣物" },
];
